title: Care By Nurse
email: info@carebynurse.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blogv14" # Corrected: This should be your repository name.
url: "https://veesood.github.io" # Corrected: This should be your GitHub Pages domain.
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate # Added: This is the plugin for pagination.

# Pagination settings
paginate: 5 # Sets the number of posts per page. You can change this number.
paginate_path: "/page:num/" # Defines the URL for paginated pages (e.g., /page2/).

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be re-included by adding them to the `include:` key.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Custom settings for HTML posts
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

collections:
  posts:
    output: true
    permalink: /:title.html

include: ["_pages"]
